# Generated by Django 3.0.7 on 2020-07-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200628_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='bio',
            field=models.TextField(max_length=100, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuários'), ('lni-mobile', 'Mobile'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
    ]
